spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mybatis_crud
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 80
#mybatis:
#  config-location: classpath:mybatis/mybatis‐config.xml  #全局配置文件
#  mapper-locations: classpath:mybatis/mapper/*.xml       #sql映射文件
logging:
    level:
      com.dmchrl.mapper: DEBUG

mybatis-plus:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  global-config:
    db-config:
      #id-type: uuid
      logic-not-delete-value: 0
      logic-delete-value: 1
  configuration:
    map-underscore-to-camel-case: true

